<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../CasImpactCacheRepair.cs" Link="CasImpactCacheRepair.cs" />
    <Compile Include="../../WeakIdentitySet.cs" Link="WeakIdentitySet.cs" />
  </ItemGroup>
</Project>
